### ISSUE TITLE
add-on is not checking for deactivated BT-Devices

### ISSUE THREAD

**Issue by MegaBarf** [SSMCD/bluetti2mqtt#19]
When using RaspberryPi with BT and WLAN I ran into connection problems with the onboard BT from the Pi (I use a 3b and a 4) where the connection randomly drops and at some point it does not reconnect again. I fixed that by using a USB BT dongle.

With the latest version of the addon it looks like it uses whatever BT device he finds. I saw this by removing the USB dongle and having the onboard BT disabled in HA and still get a connection to the Bluetti getting me the problem from above again.

Is it possible to a) check HA for disabled devices or b) make the BT-Device configurable?

**Comment by SSMCD** [comment]
I recommend disabling the troublesome on-board Bluetooth adapter entirely, at the system level.  Here's a guide on one method using ssh on an RPi running HAOS: https://community.home-assistant.io/t/disable-bluetooth/56048/13

Disabling the adapter in the Home Assistant integrations tab does nothing.  This addon does not communicate with HA in that way.

It may be possible to modify [bluetti_mqtt](https://github.com/warhammerkid/bluetti_mqtt) to allow for a choice of BT devices (hci0, hci1, etc.) but that is beyond the scope of this addon.

**Comment by theo1815** [comment]
Unfortunately, the connection via ESP Bluetooth Proxy doesn't work for me. The scan detects the Bluetti A200max but no connection is established. It works perfectly within range of the internal Bluetooth adapter of the Intel NUC. If I bring the Bluetti back within range of the Bluetooth proxy, it works until the next reconnection. Please help.
![Proxy](https://github.com/user-attachments/assets/55e428a1-3319-403b-973c-a2aad858dee8)

**Comment by harrolf** [comment]
I'm using ESPHome Bluetooth proxy as well and this is the error I get.

```
2024-12-06 14:21:19 ERROR    MQTT error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/mqtt_client.py", line 513, in run
    async with Client(
  File "/usr/local/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 822, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 390, in connect
    raise MqttError(str(error)) from None
asyncio_mqtt.error.MqttError: [Errno -2] Name does not resolve
2024-12-06 14:21:19 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/device_handler.py", line 31, in run
    await asyncio.gather(*(polling_tasks + pack_polling_tasks + [manager_task]))
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/bluetooth/manager.py", line 20, in run
    await BleakScanner.discover()
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 242, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 152, in __aenter__
    await self._backend.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 179, in start
    adapter_path = manager.get_default_adapter()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 299, in get_default_adapter
    raise BleakError("No Bluetooth adapters found.")
bleak.exc.BleakError: No Bluetooth adapters found.
2024-12-06 14:21:19 INFO     Shutting down...
```
