### ISSUE TITLE
Bluetooth Proxy

### ISSUE THREAD

**Issue by spectre338** [SSMCD/bluetti2mqtt#51]
Is it possible to use over a Bluetooth proxy or it is limited to only the BT attached to HAOS?

**Comment by bonsaijogi** [comment]
For me it works with an M5Stack Atom Lite
https://esphome.io/projects/?type=bluetooth

**Comment by harrolf** [comment]
How did you manage as I'm using ESPHome Bluetooth proxy as well and this is the error I get:

```
2024-12-06 14:21:19 ERROR    MQTT error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/mqtt_client.py", line 513, in run
    async with Client(
  File "/usr/local/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 822, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 390, in connect
    raise MqttError(str(error)) from None
asyncio_mqtt.error.MqttError: [Errno -2] Name does not resolve
2024-12-06 14:21:19 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/device_handler.py", line 31, in run
    await asyncio.gather(*(polling_tasks + pack_polling_tasks + [manager_task]))
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/bluetooth/manager.py", line 20, in run
    await BleakScanner.discover()
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 242, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 152, in __aenter__
    await self._backend.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 179, in start
    adapter_path = manager.get_default_adapter()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 299, in get_default_adapter
    raise BleakError("No Bluetooth adapters found.")
bleak.exc.BleakError: **No Bluetooth adapters found**.
2024-12-06 14:21:19 INFO     Shutting down...
```

**Comment by bonsaijogi** [comment]
I'm sorry, I can't help you any further. Everything has not been working reliably for some time now. I have no idea whether it is due to Bluetti2MQTT, MQTT or ESPHome. 

At most, data still arrives when I restart Bluetti2MQTT and ESPHome, but even that is not always the case.

**Comment by mkg500** [comment]
I'm having the exact same issue. its searching for an adapter but the esp32 is a proxy. I am so new to this stuff I've spent the past 12 hours trying to trouble shoot this and got no where. Im so close to just scrapping my whole idea of making my Van smart...

**Comment by do-while** [comment]
I also only have an ESPHome Bluetooth proxy, the Home Assistant runs in a VM. In the new virtualization you can see the Bluetti in the Bluetooth network. Bluetti2MQTT still reports “No Bluetooth adapters found”

**Comment by dezral** [comment]
+1 
im using the "slzb-06" https://www.aliexpress.com/item/1005004942648430.html compiled firmware via esphome to have Bluetooth proxy enabled and works with other Bluetooth devices like some from Shelly and a few xiaomi.

if there is anything I can help test please reach out, i do code some my self like python and stuff.

for what i can see i use normal bthome and bluetooth in home assistant at least my other devices that are supported just pop up normally.
