### ISSUE TITLE
BT Errors in HA Core Logs

### ISSUE THREAD

**Issue by TobiGitHubi** [SSMCD/bluetti2mqtt#53]
Until 2024.12.x Updates of HA I got Error messages in the HA Core Logs, any hints for a beginner to fix this?
O=r will it be fixed in a future update?

**Error1:**
Logger: custom_components.bluetti_bt.coordinator
Quelle: helpers/update_coordinator.py:379
Integration: Bluetti BT ([Dokumentation](https://github.com/Patrick762/hassio-bluetti-bt), [Probleme](https://github.com/Patrick762/hassio-bluetti-bt/issues))
Erstmals aufgetreten: 23. Dezember 2024 um 21:59:38 (8 Vorkommnisse)
Zuletzt protokolliert: 14:01:33
Unexpected error fetching Bluetti polling coordinator data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/coordinator.py", line 78, in _async_update_data
    return await self.reader.read_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/bluetti_bt_lib/bluetooth/device_reader.py", line 155, in read_data
    await self.client.disconnect()
  File "/usr/local/lib/python3.13/site-packages/habluetooth/wrappers.py", line 404, in disconnect
    return await self._backend.disconnect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 409, in disconnect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/dbus_fast/aio/message_bus.py", line 385, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 19, in dbus_fast.aio.message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 775, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 636, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 374, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
  File "src/dbus_fast/_private/unmarshaller.py", line 317, in dbus_fast._private.unmarshaller.Unmarshaller._read_sock_with_fds
EOFError

**Error2:**
Logger: custom_components.bluetti_bt.bluetti_bt_lib.bluetooth.device_reader
Quelle: custom_components/bluetti_bt/bluetti_bt_lib/bluetooth/device_reader.py:143
Integration: Bluetti BT ([Dokumentation](https://github.com/Patrick762/hassio-bluetti-bt), [Probleme](https://github.com/Patrick762/hassio-bluetti-bt/issues))
Erstmals aufgetreten: 05:29:14 (1 Vorkommnisse)
Zuletzt protokolliert: 05:29:14
Bleak error: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
--------------------------------------------------------

Thanks for reading and have a great christmas time...

**Comment by TobiGitHubi** [comment]
Updatet to 1.4.1 today, will have a look what happened now...
